remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Documentación

nombres: Nicolas Garcia Ossa
submodulo: Introducción a la programación
periodo: 2023-2
url_foto: https://firebasestorage.googleapis.com/v0/b/docuementos-12812.appspot.com/o/foto.jpeg?alt=media&token=0bd6dd30-d6ff-405d-a4ba-5fbf65bb6def&_gl=1*1i6nst3*_ga*OTQwMDI4MC4xNjk2MTg3MjAx*_ga_CW55HF8NVT*MTY5NjE4NzIwMS4xLjEuMTY5NjE4NzU1Mi40Ny4wLjA.
