remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Documentación

nombres: Nicolas Garcia Ossa
submodulo: Introducción a la programación
periodo: 2023-2
url_foto: https://firebasestorage.googleapis.com/v0/b/docuementos-12812.appspot.com/o/Escudo%20padilla.png?alt=media&token=6c2f540e-1c7e-40b2-94af-7bf75a0dd1f4&_gl=1*zg89pd*_ga*OTQwMDI4MC4xNjk2MTg3MjAx*_ga_CW55HF8NVT*MTY5NjE4NzIwMS4xLjEuMTY5NjE4NzI5NC4zOC4wLjA.
